name: SMPItems
version: ${project.version}
main: me.totalfreedom.smpitems.SMPItems
api-version: 1.15
authors: [lildarke, lildarkee, fionnn, sguare]
description: Items for SMP. Based on https://docs.google.com/spreadsheets/d/1CzddRDa38kimHsFf5tJgeP0CZoR2P5yUBMJwnQJ1LIU/edit
commands:
  smpspawnmob:
    description: Spawn a mob from the SMPItems plugin.
    usage: /<command> <mob>
    aliases: [ssm, spawntubby]
  smpgiveitem:
    description: Give yourself an item from the SMPItems plugin.
    usage: /<command> <item>
    aliases: [sgi, smpgive]
  smpsetframe:
    description: Set the coordinates of a portal frame for the Tubby Ender Dragon.
    usage: /<command> <frameid> <x> <y> <z>
    aliases: [ssf, smpframe]
  smpitems:
    description: Provides information about SMPItems, or optionally reloads the config file.
    usage: /<command> <reload>
    aliases: [sinfo]
  smpwiki:
    description: In-depth guide for SMPItems.
    usage: /<command>
    aliases: [smpitemswiki, siwiki, wiki]
  smpkilltubbies:
    description: Kills every tubby mob
    usage: /<command>
    aliases: [killtubbies]
  toggletubby:
    description: Toggle the tubby broadcast.
    usage: /<command>
    aliases: [tt]